---
title: "Bipin"
output: html_document
date: "2022-11-19"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
footballgames <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/games.csv')

##### derive categorical variable #####
# replace NA's in tie column with string 0
footballgames$tie[is.na(footballgames$tie)] <- "0"
# replace ties with string 1 instead of string with team name
for(i in 1:5324){
  if(footballgames$tie[i] != "0"){
    footballgames$tie[i] <- "1"
    i < i+1
  }
  else{
    i <- i+1
  }
}

# treat tie as categorical
footballgames$tie <- as.factor(footballgames$tie)


# get structure to check if tie is not a factor
str(footballgames)

```

```{r, echo = TRUE, results = 'hide'}
# replace ties with string 1 instead of string with team name
for(i in 1:5324){
  if(footballgames$tie[i] == 1){
    footballgames$winner[i] <- "Tie"
    i < i+1
  }
  else{
    i <- i+1
  }
}

footballgames
```

```{r}

#Filter out the data for games played by New England Patriots
bbdata<-subset(footballgames, home_team=="New England Patriots"|away_team=="New England Patriots")

library(tidyverse)
library(magrittr)
library(dplyr)
library(ggplot2)
library(plotly)

ggdata<-bbdata %>% group_by(year) %>% count(winner)

#Filter out data for number of games won by New England Patriots
fdata<-subset(ggdata, winner=="New England Patriots")

plot1<-ggplot(data=fdata, aes(x=year, y=n))+geom_line()
plot1
```

```{r}
#Line plot of number of games won by 5 selected teams each year
a=footballgames %>% group_by(year) %>%  count(winner)
b = subset(a, winner== "Baltimore Ravens"|winner=="Chicago Bears"|winner=="Denver Broncos"|winner=="Miami Dolphins"|winner=="New England Patriots")

plot2<- ggplot(data= b, aes(year, n))+geom_line(aes(color=winner))+ xlab("Year")+ylab("Number of wins")+ggtitle("Number of games won by selected teams each year")

ggplotly(plot2)
```

#Interactive scatterplot of points won vs yards won for selected teams

```{r}
m= subset(footballgames, winner== "Baltimore Ravens"|winner=="Chicago Bears"|winner=="Denver Broncos"|winner=="Miami Dolphins"|winner=="New England Patriots")

plot3<-ggplot(data= m)+ geom_point(aes(pts_win, yds_win,color= winner)) +xlab("Points Won")+ ylab("Yards Win")

ggplotly(plot3)  
```


```{r}
library(dplyr)
#AFC vs NFC teams list
afc_teams<- c("Cleveland Browns","Baltimore Ravens","Pittsburgh Steelers","Cincinnati Bengals","Miami Dolphins","Buffalo Bills","New York Jets","New England Patriots", "Kansas City Chiefs","Los Angeles Chargers","Denver Broncos","Las Vegas Raiders","Tennessee Titans","Houston Texans","Indianapolis Colts","Jacksonville Jaguars")

nfc_teams<-c("Minnesota Vikings","Chicago Bears","Detroit Lions","Green Bay Packers","New York Giants","Dallas Cowboys","Washington Redskins","Philadelphia Eagles","Arizona Cardinals","Los Angeles Rams","Seatlle Seahawks","San Franscisco 49ers","Atlanta Falcons","Tampa Bay","Carolina Panthers ","New Orlean Saints") 
```

```{r}
#Created a new column in original dataset called 'division' the teams play in by home team.

for(i in 1:5324){
  if(footballgames$home_team[i] %in% afc_teams){
    footballgames$divison[i]<- "AFC"

  }
  else{
    footballgames$divison[i]<- "NFC"

  }
}
```

```{r}
#Comparing the number of games won by AFC team vs NFC team. 
for(i in 1:5324){
  if(footballgames$winner[i]=="Tie"){
     footballgames$won_by[i]<-"Tied"
  }
  else if(footballgames$winner[i]%in% afc_teams){
    footballgames$won_by[i]<-"AFC_team_win"
  }
  else{
    footballgames$won_by[i]<-"NFC_team_win"  
    }
}

##Calculate the percentage of game won by NFC team at home.
table(footballgames$won_by)


```


```{r}
#Percentage of game won at home by NFC teams whenever they played AFC teams.

###First create a data with home team being NFC team and away team being AFC team. 
homewin_nfc<-filter(footballgames, footballgames$home_team %in% nfc_teams & footballgames$away_team %in% afc_teams )

###To find out which division won when NFC played at home. 
for(i in 1:364){
  if(homewin_nfc$winner[i]=="Tie"){
     footballgames$win_div[i]<-"Tied"
  }
  else if(homewin_nfc$winner[i]%in% afc_teams){
    homewin_nfc$win_div[i]<-"AFC_Win"
  }
  else{
    homewin_nfc$win_div[i]<-"NFC_Win"  
  }
}

#Calculate the percentage of game won by NFC team at home.
(table(homewin_nfc$win_div)/364)*100

#NFC_Win = 55.5%
#AFC_Win = 44.5%

#Percentage of game won at home by AFC teams whenever they played NFC teams.

homewin_afc<-filter(footballgames, footballgames$home_team %in% afc_teams & footballgames$away_team %in% nfc_teams )

###To find out which division won when AFC played at home. 
for(i in 1:366){
  if(homewin_afc$winner[i]=="Tie"){
     homewin_afc$win_div[i]<-"Tied"
  }
  else if(homewin_afc$winner[i]%in% afc_teams){
    homewin_afc$win_div[i]<-"AFC_Win"
  }
  else{
    homewin_afc$win_div[i]<-"NFC_Win"  
  }
}
#Calculate the percentage of game won by NFC team at home.
(table(homewin_afc$win_div)/366)*100

#AFC_Win = 61.0%
#NFC_Win = 38.0%
#Tied = 1%   
```

```{r}
#Create a new column 'HT' to find whose home team was: AFC or NFC

for (i in 1:5324){
  if(footballgames$home_team[i] %in% afc_teams){
    footballgames$HT[i]<- "AFC"
  }
  else{
    footballgames$HT[i]<-"NFC"
  }
}

table(footballgames$HT)


#Create a new column 'AT' to find whose away team was: AFC or NFC
for (i in 1:5324){
  if(footballgames$away_team[i] %in% afc_teams){
    footballgames$AT[i]<- "AFC"
  }
  else{
    footballgames$AT[i]<-"NFC"
  }
}

table(footballgames$AT)


#Find the games AFC team vs NFC team, home and away. 

afcvsnfc<- filter(footballgames, HT=="AFC" & AT=="NFC"| HT=="NFC" & AT=="AFC")

#Find out who won against AFC vs NFC only, home and away. 
for(i in 1:1536){
  if(afcvsnfc$winner[i]=="Tie"){
    afcvsnfc$winner[i]=="Tied"
    }
    else if(afcvsnfc$winner[i] %in% afc_teams){
    afcvsnfc$win_team[i]<- "AFC"
    }
    else{
    afcvsnfc$win_team[i]<- "NFC"
    }  
}

#Calculate the percentage of games won by NFC and AFC teams.
(table(afcvsnfc$win_team)/1536)*100

#Whenever, AFC played NFC either home or away:
#AFC won 53.6% of the games vs. NFC 46.4%

#Plot of AFC vs NFC playing each other only. 
plot4<-ggplot(data = afcvsnfc) +
  geom_bar(mapping = aes(x = win_team, y = ..prop.., group=1), stat="count")+xlab("Winning Team")+ylab("Winning Percentage %")
plot4
```








