---
title: "STAT 850 Report"
author: "Paulus Hermanto, Andrew Ker, Bipin Poudel"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Loading in the final data
```{r}
footballgames <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/games.csv')

##### derive categorical variable #####
# replace NA's in tie column with string 0
footballgames$tie[is.na(footballgames$tie)] <- "0"
# replace ties with string 1 instead of string with team name
for(i in 1:5324){
  if(footballgames$tie[i] != "0"){
    footballgames$tie[i] <- "1"
    i < i+1
  }
  else{
    i <- i+1
  }
}

# treat tie as categorical
footballgames$tie <- as.factor(footballgames$tie)


# get structure to check if tie is not a factor
str(footballgames)

```


#Interactive line plots for the number of wins for selected teams. 
```{r}
library(tidyverse)
library(magrittr)
library(dplyr)
library(ggplot2)
library(plotly)

a=footballgames %>% group_by(year) %>%  count(winner)
b = subset(a, winner== "Baltimore Ravens"|winner=="Chicago Bears"|winner=="Denver Broncos"|winner=="Miami Dolphins"|winner=="New England Patriots")

plot1<- ggplot(data= b, aes(year, n))+geom_line(aes(color=winner))+ xlab("Year")+ylab("Number of wins")+ggtitle("Number of games won by selected teams each year")

ggplotly(plot1)

```
